function figures = plot_addition_summary(summaryFile, outputDirectory)
% Запуск без аргументов позволяет выбрать addition-summary.csv.
% Или:
% plot_addition_summary('D:\path\addition-summary.csv')

close all

figures = gobjects(0);

if nargin < 1 || isempty(summaryFile)
    startFolder = fullfile(fileparts(mfilename('fullpath')), '..', 'results');

    [file, folder] = uigetfile( ...
        fullfile(startFolder, '*.csv'), ...
        'Выберите addition-summary.csv');

    if isequal(file, 0)
        return;
    end

    summaryFile = fullfile(folder, file);
end

summaryFile = char(summaryFile);

if nargin < 2 || isempty(outputDirectory)
    outputDirectory = fullfile(fileparts(summaryFile), 'plots-matlab');
end


%% Необходимые столбцы

required = { ...
    'added_elements', ...
    'scuff_time_mean_s', ...
    'feko_time_mean_s', ...
    's11_scuff_mean_db', ...
    's11_feko_mean_db', ...
    'gmax_scuff_mean_dbi', ...
    'gmax_feko_mean_dbi', ...
    's11_error_db_mean', ...
    'gmax_error_db_mean' ...
    };


%% Чтение CSV

options = detectImportOptions( ...
    summaryFile, ...
    'Delimiter', ',', ...
    'VariableNamingRule', 'preserve');

missing = setdiff(required, options.VariableNames);

if ~isempty(missing)
    error( ...
        'AdditionPlot:MissingColumns', ...
        'В CSV отсутствуют столбцы: %s', ...
        strjoin(missing, ', '));
end

numericColumns = required;

if ismember('frequency_hz', options.VariableNames)
    numericColumns{end+1} = 'frequency_hz';
end

options = setvartype( ...
    options, ...
    numericColumns, ...
    'double');

data = readtable(summaryFile, options);


%% Проверка данных

if isempty(data)
    error( ...
        'AdditionPlot:EmptyFile', ...
        'Файл не содержит данных.');
end

if any( ...
        ~isfinite(data.added_elements) | ...
        data.added_elements < 1 | ...
        data.added_elements ~= fix(data.added_elements))

    error( ...
        'AdditionPlot:InvalidK', ...
        'added_elements должен содержать положительные целые числа.');
end


%% Частота

if ~ismember('frequency_hz', data.Properties.VariableNames)

    data.frequency_hz = zeros(height(data), 1);

elseif any( ...
        ~isfinite(data.frequency_hz) | ...
        data.frequency_hz <= 0)

    error( ...
        'AdditionPlot:InvalidFrequency', ...
        'frequency_hz должен содержать положительные конечные значения.');
end

frequencyValues = unique(data.frequency_hz);


%% Проверка повторяющихся K

for frequency = frequencyValues'

    block = data(data.frequency_hz == frequency, :);

    if numel(unique(block.added_elements)) ~= height(block)

        error( ...
            'AdditionPlot:DuplicateK', ...
            'Обнаружены повторяющиеся значения K при частоте %.12g Гц.', ...
            frequency);

    end
end


%% Создание папки для графиков

if ~isfolder(outputDirectory)

    [ok, message] = mkdir(outputDirectory);

    if ~ok
        error( ...
            'AdditionPlot:OutputDirectory', ...
            '%s', ...
            message);
    end
end


%% Цвета

figures = gobjects(numel(frequencyValues), 1);

colors = [ ...
    0.08, 0.35, 0.65; ...
    0.80, 0.18, 0.12 ...
    ];


%% Построение графиков

for index = 1:numel(frequencyValues)

    frequency = frequencyValues(index);

    block = sortrows( ...
        data(data.frequency_hz == frequency, :), ...
        'added_elements');

    k = block.added_elements;


    %% Создание окна

    fig = figure( ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');

    figures(index) = fig;


    %% Компоновка

    layout = tiledlayout( ...
        fig, ...
        2, 3, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');


    %% 1. Среднее время расчёта

    ax = nexttile(layout);

    plot_pair( ...
        ax, ...
        k, ...
        block.scuff_time_mean_s, ...
        block.feko_time_mean_s, ...
        colors);

    title(ax, 'Среднее время расчёта');
    ylabel(ax, 'Время, с');


    %% 2. Отношение FEKO / Schur

    ax = nexttile(layout);

    ratio = ...
        block.feko_time_mean_s ./ ...
        block.scuff_time_mean_s;

    ratio( ...
        block.scuff_time_mean_s <= 0 | ...
        ~isfinite(ratio)) = NaN;

    plot( ...
        ax, ...
        k, ...
        ratio, ...
        '-d', ...
        'Color', [0.15, 0.15, 0.15], ...
        'LineWidth', 1.5, ...
        'MarkerSize', 6);

    title(ax, 'Отношение времени FEKO / Schur');
    ylabel(ax, 'Отношение времени');


    %% 3. S11

    ax = nexttile(layout);

    plot_pair( ...
        ax, ...
        k, ...
        block.s11_scuff_mean_db, ...
        block.s11_feko_mean_db, ...
        colors);

    title(ax, 'Среднее значение S_{11}');
    ylabel(ax, 'S_{11}, дБ');


    %% 4. Gmax

    ax = nexttile(layout);

    plot_pair( ...
        ax, ...
        k, ...
        block.gmax_scuff_mean_dbi, ...
        block.gmax_feko_mean_dbi, ...
        colors);

    title(ax, 'Среднее значение G_{max}');
    ylabel(ax, 'G_{max}, дБи');


    %% 5. Ошибка S11

    ax = nexttile(layout);

    plot( ...
        ax, ...
        k, ...
        block.s11_error_db_mean, ...
        '-o', ...
        'Color', colors(1, :), ...
        'LineWidth', 1.5, ...
        'MarkerSize', 6);

    title(ax, 'Средняя абсолютная ошибка S_{11}');
    ylabel(ax, 'Абсолютная разность, дБ');


    %% 6. Ошибка Gmax

    ax = nexttile(layout);

    plot( ...
        ax, ...
        k, ...
        block.gmax_error_db_mean, ...
        '-s', ...
        'Color', colors(2, :), ...
        'LineWidth', 1.5, ...
        'MarkerSize', 6);

    title(ax, 'Средняя абсолютная ошибка G_{max}');
    ylabel(ax, 'Абсолютная разность, дБ');


    %% Общие настройки осей

    axesObjects = findall(fig, 'Type', 'axes');

    for ax = axesObjects'

        xlabel(ax, 'Количество добавленных элементов, K');

        grid(ax, 'on');

        set( ...
            ax, ...
            'GridAlpha', 0.18, ...
            'LineWidth', 0.8, ...
            'Box', 'on');

        fit_x_axis_to_data(ax);

    end


    %% Общий стиль

    set( ...
        findall(fig, '-property', 'FontName'), ...
        'FontName', 'Times New Roman');

    set( ...
        findall(fig, '-property', 'FontUnits'), ...
        'FontUnits', 'points');

    set( ...
        findall(fig, '-property', 'FontSize'), ...
        'FontSize', 14);

    set( ...
        findall(fig, '-property', 'FontAngle'), ...
        'FontAngle', 'italic');

    set( ...
        findall(fig, '-property', 'FontWeight'), ...
        'FontWeight', 'normal');

    drawnow;


    %% Сохранение

    name = sprintf( ...
        'addition-summary-frequency-%02d', ...
        index);

    exportgraphics( ...
        fig, ...
        fullfile(outputDirectory, [name, '.png']), ...
        'Resolution', 200, ...
        'BackgroundColor', 'white');

    savefig( ...
        fig, ...
        fullfile(outputDirectory, [name, '.fig']));

end


fprintf( ...
    'Сохранено графиков: %d. Папка: %s\n', ...
    numel(figures), ...
    char(outputDirectory));

end



function plot_pair(ax, k, scuff, feko, colors)

plot( ...
    ax, ...
    k, ...
    scuff, ...
    '-o', ...
    'Color', colors(1, :), ...
    'LineWidth', 1.5, ...
    'MarkerSize', 6);

hold(ax, 'on');

plot( ...
    ax, ...
    k, ...
    feko, ...
    '--s', ...
    'Color', colors(2, :), ...
    'LineWidth', 1.5, ...
    'MarkerSize', 6);

hold(ax, 'off');

legend( ...
    ax, ...
    {'SCUFF-EM / дополнение Шура', 'FEKO'}, ...
    'Location', 'best');

end



function fit_x_axis_to_data(ax)

lines = findall(ax, 'Type', 'line');

validX = [];

for lineObj = lines'

    xData = lineObj.XData;
    yData = lineObj.YData;

    mask = ...
        isfinite(xData) & ...
        isfinite(yData);

    validX = [validX, xData(mask)]; %#ok<AGROW>

end

validX = unique(validX);

if isempty(validX)
    return;
end

xmin = min(validX);
xmax = max(validX);

if xmin == xmax

    xlim(ax, [xmin - 0.5, xmax + 0.5]);

else

    margin = 0.03 * (xmax - xmin);

    xlim(ax, [xmin - margin, xmax + margin]);

end

if numel(validX) <= 15
    xticks(ax, validX);
end

end